special_key: "secretsauce23214$%"
user_service_fetch_preference_url: "http://localhost:8080/api/v1/user/user-news-preferences"
news_aggregator_recent_news_url: "http://localhost:8081/api/v1/news-aggregator/news/recent"