# config.yaml
jwt_secret: "defaultsecretKey$23"
database:
  useLocal: false
  local:
    host: "localhost"
    port: 5432
    user: "postgres"
    dbname: "news_project_test_db"
    password: "A1b2c3d4e5"
  prod:
    host: "flora.db.elephantsql.com"
    port: 5432
    user: ""
    dbname: ""
    password: ""
default_preferences:
  - business
  - football
  - health
  - science
  - sports
  - politics
  - technology
  - education
  - fashion
  - food
  - football
  - healthcare-network
  - lifeandstyle
  - money
  - politics
  - sport
  - travel
  - weather
  - world
